version: 0.2

phases:
  pre_build:
    commands:
       - echo logging in to Amazon ECR...
       - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
       - echo Build started on `date`
       - echo Building the Docker image ...
       - cd Project777
       - docker build -t project777:api -f ./Project777.Api/Dockerfile .
       - docker tag project777:api $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/project777:api
  post_build:
    commands:
       - echo Build completed on `date`
       - echo Pushing the Docker image...
       - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/project777:api
       - cp Dockerrun.aws.json ../Dockerrun.aws.json
artifacts:
  files: Dockerrun.aws.json
