name: Greet User Action
run-name: ${{ github.actor}} in action on ${{ ${{ inputs.deploy_target }}}}
on: [push, pull_request]
jobs:
     greet-user:
          runs-on: ubuntu-latest
          steps:
               - run: echo "Hello" ${{github.actor}}
