name: Greet User Action
run-name: ${{ github.actor}} triggered ${{ github.event_name }}
on: [push, pull_request]
jobs:
     greet-user:
          runs-on: ubuntu-latest
          steps:
               - run: echo "Hello" ${{github.actor}}
