name: test
run-name: ${{ github.actor}} in action on ${{ github.ref-name}}
on: [push, pull_request]
jobs:
     greet-user:
          runs-on: ubuntu-latest
          steps:
               - run: echo "Hello" ${{github.actor}}
